### ISSUE TITLE
Expose multiple ports

### ISSUE THREAD

**Issue by Bekt** [jwilder/docker-gen#173]
The default template exposes only one port per container, which I find strange.

I think more than often if the container exposes multiple ports (especially via [ports](https://docs.docker.com/compose/compose-file/#ports) instead of `expose`), it makes sense to expose all those ports to the host.

If a `foo` container exposes ports 5001 and 5002 (mapped to random host ports), the reverse proxy should be able to correctly proxy `foo:5001` and `foo:5002`.

What do you think?

**Comment by danielefranceschi** [comment]
I was going to open a similar issue: as multiple vhosting is already possible via comma-separated names in VIRTUAL_HOST, multiple ports could be specified in VIRTUAL_PORT. My use case is:
```yaml
 nexus:
        image: sonatype/nexus3
        restart: always
        container_name: nexus
        environment:
            - VIRTUAL_HOST=nexuspa.netserv.it
            - VIRTUAL_PORT=8081
            - JAVA_OPTS=-Djava.awt.headless=true
        ports:
            - 8081:8081
        expose:
            - 5000
            - 5001

expose:
  - p1
  - p2
  - p3
environment:
  - VIRTUAL_HOST=a,b,c
  - VIRTUAL_PORT=p1,p2,p3
```
that results in reverse proxying a
