### ISSUE TITLE
Multiple websites

### ISSUE THREAD

**Issue by lukasoppermann** [jwilder/docker-gen#213]
Hey @jwilder or @wader, how can I use docker-gen with multiple pages?

Adding the `VIRTUAL_HOST` works fine to create 2 `server` blocks, but of course now both domains are pointing to `/var/www/html`, which does not work.

How can I point `app1` to `/var/www/html/app1` and `app2` to `/var/www/html/app2`?

Is it possible that I add another environment variable

e.g. `- ROOT_FOLDER=app1` and use it within the template? If so, how can I use it in the template?

**Comment by wader** [comment]
Hi, not sure i understand what you want to do. You mean to have one container serving multiple hostnames from different directories? then i would probably just run two containers and serve content from the app containers. Or have one app container that has the logic to serve different directories based on hostname.

Where is `/var/www/html` in your setup, is that a path inside the nginx-proxy or app container?

Maybe easiest if you give a more full config of your imagined setup? :)

**Comment by lukasoppermann** [comment]
Hey @wader,

okay, so what I want is this:

I have `app`,  `api` and `staging-app` and `staging-api` with all their own domains:
- app.domain.com
- api.domain.com
- staging-app.domain.com
- staging-api.domain.com

They all, for on docker server. I want to maybe be able to scale it out, so that I can add more nginx / php servers.

My docker setup is:

- proxy: nginx (all domains come here)
- docker-gen
- app: nginx
- api: nginx
...
- php: php-fm

Everything is in the `app` network.

Question one would be, would I create a docker php container per app?

The other problem is, `docker-gen` creates a conf file on proxy. All domains go to proxy and need to be directed to the apps. 

However if I just have one php

```
  app:
        image: shippingdocker/nginx:latest
        volumes:
            - ./app:/var/www/html
        networks:
            - appnet
        environment:
            - VIRTUAL_HOST=add.domain.com
    # php
    php:
        image: shippingdocker/php:latest
        container_name: php
        volumes:
            - ./app:/var/www/html/app # here I would need to add all folders
            - ./api:…
        networks:
            - appnet
```

If I would have multiple php instances (makes sense to me, but does it?)

```
  app:
        image: shippingdocker/nginx:latest
        volumes:
            - ./app:/var/www/html
        networks:
            - appnet
        environment:
            - VIRTUAL_HOST=add.domain.com
    # php
    appphp:
        image: shippingdocker/php:latest
        container_name: appphp
        volumes_from:
            - app
        networks:
            - appnet
```

But now I need to tell the `proxy` nginx where to look for php when a user comes via `add.domain.com`, or `api.domain.com`.

Is this understandable? Do you need any more information? If you have a completely different, but better solution, please let me know.
