### ISSUE TITLE
Bad IP when container have multiple network in docker-compose

### ISSUE THREAD

**Issue by Nasjoe** [jwilder/docker-gen#223]
Hi.
I use docker-compose to up all my services.
I have created many network for different services : nginx-proxy, postgresql, frontend etc...

i create a new network with "docker network create -d bridge nginx-proxy"

My docker-compose nginx-proxy look like :

```
version: '2'
networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
         [certs, conf etc......]
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-tier

  docker-gen:
    image: jwilder/docker-gen
    depends_on:
      - nginx
    container_name: docker-gen
    volumes_from:
      - nginx
    volumes:
      - "[...]nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    command: -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-gen:
      [some good conf, it's work like a charm]


```

All works very well when i launch an app with the same networks as nginx-conf like that :

```
version: '2'
networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  django:
    build: .
    ports:
      - "8066:80"
    networks:
      - proxy-tier
    command: python manage.py runserver 0.0.0.0:80
    environment:
      VIRTUAL_HOST: "myhost.mydns.com"
      VIRTUAL_PORT: "8066"
      LETSENCRYPT_HOST: "myhost.mydns.com"
      LETSENCRYPT_EMAIL: "me@mydns.com"
```

The django service are on the same network as the nginx-proxy, and the docker-gen build a good upstream with the ip of the django container (172.21.0.5:8066)

The problem appear when i start a container with two or more network, like a postgresql :

```
networks:
  proxy-tier:
    external:
      name: nginx-proxy
  postgres-tier:
    external:
      name: postgresql-network

services:
  django:
    build: .
    ports:
      - "8066:80"
    networks:
      - proxy-tier
      - postgres-tier
    command: python manage.py runserver 0.0.0.0:80
    environment:
      VIRTUAL_HOST: "myhost.mydns.com"
      VIRTUAL_PORT: "8066"
      LETSENCRYPT_HOST: "myhost.mydns.com"
      LETSENCRYPT_EMAIL: "me@mydns.com"

  postgresql:
      image: postgresql
      expose:
          - 5432
      networks:
          - postgres-tier

```
I don't want the postgresql and nginx on the same network. And all work well like that. Django and Postgres can talk together, and nginx can talk to Django only.

So Django are now on two networks : proxy-tier (172.21.0.x) and postgres-tier ( 172.24.0.x ).

My problem is this :

Docker-gen look at the ip of the django and  randomly fills the nginx config file with the proxy-tier ip (172.21.0.4) or the postgres-tier (172.24.0.12). He did not choose the ip in common with nginx all the time.
So, i have sometime (when i launch new services) a nginx conf file with upstream ip that nginx can not talk.

Did you know how can i fix this ? Actually, i add nginx in all network, but it seem a little hacky, and not very secure. Not fully automated too, cause i can't create new network without relaunch all my nginx-proxy docker-compose for add the new network.

Thank you.
