### ISSUE TITLE
-include-stopped containers is working normally?

### ISSUE THREAD

**Issue by renanberto** [jwilder/docker-gen#233]
- A collector (collectDaemon)
- Two servers (server1, server2)

### Compose:
```
version: '2'
services:
 
  server1:
    build: .
    hostname: server1
    container_name: server1
    environment:
      VIRTUAL_HOST: "server1.foo.bar"
      SERVER_HOST: "cloudApp"
      HOST_FQDN: "cloudapp.foo.bar"
 
  server2:
    build: .
    hostname: server2
    container_name: server2
    environment:
      VIRTUAL_HOST: "server2.foo.bar"
      SERVER_HOST: "cloudApp"
      HOST_FQDN: "cloudapp.foo.bar"

  collect_daemon:
    build: ../.
    hostname: CollectDaemon
    container_name: collectdaemon
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVER_HOST: "cloudApp"
      HOST_FQDN: "cloudapp.foo.bar"
```

### Dockerfile collect_daemon:

```
FROM debian:wheezy
MAINTAINER Jason Wilder <mail@jasonwilder.com>

ENV VERSION 0.7.3
ENV DOWNLOAD_URL https://github.com/jwilder/docker-gen/releases/download/$VERSION/docker-gen-linux-amd64-$VERSION.tar.gz
ENV DOCKER_HOST unix:///var/run/docker.sock

RUN deps=' \
                curl ca-certificates \
        '; \
        set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends $deps \
        && curl -L $DOWNLOAD_URL | tar -C /usr/local/bin -xvz \
        && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $deps \
        && apt-get clean -y \
        && rm -rf /var/lib/apt/lists/*
WORKDIR /var/lib
ADD . /var/lib
ENTRYPOINT ["/usr/local/bin/docker-gen", "-config", "/var/lib/file.cfg"]
```
### File.cfg:

```
[[config]]
template = "file.tmpl"
dest = "/tmp/collect_history.cfg"
watch = true
include-stopped = true
```
### On stop one container:

```
2017/01/25 13:37:00 Generated '/tmp/collect_history.cfg' from 3 containers
2017/01/25 13:37:00 Watching docker events
2017/01/25 13:37:00 Contents of /tmp/collect_history.cfg did not change. Skipping notification ''
2017/01/25 13:40:10 Received event die for container dcdd40ab56ae
2017/01/25 13:40:10 Received event stop for container dcdd40ab56ae
2017/01/25 13:40:10 Generated '/tmp/collect_history.cfg' from 2 containers
2017/01/25 13:40:10 Contents of /tmp/collect_history.cfg did not change. Skipping notification ''
```

I have also tried to go straight through a parameter with `-include-stopped` but it also did not work.
My final question is really whether this parameter works for all exposed scenarios
Thank you!
