### ISSUE TITLE
Not finding my containers in proxy_pass

### ISSUE THREAD

**Issue by c4d3r** [jwilder/docker-gen#235]
I am having a container that exposes port 3000 like this:
```
server.connection({port: `3000, host: '0.0.0.0'});
```

and im trying to make a nginx configuration as defined here:
 ```
  api:
    restart: always
    ports: ["3000:3000"]
    environment:
      - VIRTUAL_HOST=mydomain.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=admin@mydomain.com
  nginx:
    image: nginx
    container_name: nginx
    ports: ["80:80"]
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_hosts:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_html:/usr/share/nginx/html

  nginx-gen:
    build: ./nginx-gen
    container_name: nginx-gen
    volumes_from:
      - nginx
    depends_on:
      - api
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/templates:/etc/docker-gen/templates
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
```

the file gets configured like this after running docker-compose up
```
upstream 52888a4f06110de6a1e83b178281120facc9295b {
                        # mycontainer_api_1
                        server 172.18.0.3:3000;
}
```

for getting my template into a container i use:
```
FROM jwilder/docker-gen

COPY ./nginx.tmpl /etc/docker-gen/templates/nginx.tmpl


ENTRYPOINT ["/usr/local/bin/docker-gen", "-notify-sighup", "nginx", "-watch", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]

```

however, when i browse to *mydomain.com* it says unable to connect, indicating that the container is not available?

anybody has any thoughts on how to solve this?
