### ISSUE TITLE
Nginx Proxy + Letsencrypt + OpenVPN causes "no servers are inside upstream in /etc/nginx/conf.d/default.conf"

### ISSUE THREAD

**Issue by Raballeww** [jwilder/docker-gen#249]
I am using Nginx Proxy in combination with the Letsencrypt Proxy Companion and a OpenVPN Container. Goal is to have some containers running public and some behind the VPN. Therefore I created the following docker-compose.yml

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/letsencrypt/nginx:/etc/nginx/certs:ro
      - /docker/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      proxy:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /docker/letsencrypt/nginx:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      proxy:

  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn
    restart: always
    volumes:
      - /docker/openvpn:/etc/openvpn
    environment:
      - VIRTUAL_HOST=vpn.domain.com
      - LETSENCRYPT_HOST=vpn.domain.com
      - LETSENCRYPT_EMAIL=letsencrypt@domain.com
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    networks:
      private:
        ipv4_address: 172.200.0.10

# PUBLIC exposed service
  public-hello:
    image: tutum/hello-world
    expose:
      - '80'
    environment:
      - VIRTUAL_HOST=hello.domain.com
      - LETSENCRYPT_HOST=hello.domain.com
      - LETSENCRYPT_EMAIL=letsencrypt@domain.com
    networks:
      proxy:

# VPN hidden service
  hidden-hello:
    image: tutum/hello-world
    ports:
      - 80
    networks:
      private:
        ipv4_address: 172.200.0.11


networks:
  private:
    ipam:
      config:
        - subnet: 172.200.0.0/16
  proxy:
``` 

I need to create two separate networks, `proxy` for public services and `private` for private services since this is a nice way to split the services. The default docker bridge network is not working here. Running docker-compose and connecting to the VPN allows me to access `172.200.0.11` without a problem. It does not matter if the VPN Client is connected to the VPN or not. There is no way to access `hello.domain.com`. All I get is an error using `docker logs nginx-proxy command`. 

`nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:69`

I am running the latest images of all services. The `nginx-proxy` restarts a few times but nothing happens.

Docker version 1.12.6, build 78d1802
docker-compose version 1.9.0, build 2585387

Help appreciated!
