### ISSUE TITLE
unable to parse template: template: docker-gen:2208: unexpected unrecognized character in action: U+0000 in command

### ISSUE THREAD

**Issue by udono** [jwilder/docker-gen#50]
Hi,
I am not sure if this issue is related to docker-gen.
When I try to run your examples with http://fig.sh I get the following error message:

    dockergen_1 | 2014/12/21 14:14:37 unable to parse template: template: docker-gen:2208: 
    unexpected unrecognized character in action: U+0000 in command

My fig.yml looks like this:

        nginx:
          image: nginx
          volumes:
            - /tmp/nginx:/etc/nginx/conf.d
          ports:
            - "80:80"

        dockergen:
          image: jwilder/docker-gen:0.3.6
          command: /usr/local/bin/docker-gen -notify-sighup nginx -watch --only-published /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
          volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - /tmp/templates:/etc/docker-gen/templates
          volumes_from:
            - nginx

Ideas?

**Comment by andreaskoch** [comment]
Hi,
I encountered exactly the same error but I found the solution.

The reason by docker-gen does not work is because the [entrypoint](https://github.com/jwilder/docker-gen/blob/master/Dockerfile#L10) of the `jwilder/docker-gen` image is already set to `docker-gen`, so you basically pass `/usr/local/bin/docker-gen` as the first argument to it and thats why it isn't working.

If you modify your Fig file like this it will work:

```yaml
nginx:
  image: nginx
  volumes:
    - /tmp/nginx:/etc/nginx/conf.d
  ports:
    - "80:80"

dockergen:
  image: jwilder/docker-gen:0.3.6
  command: -notify-sighup nginx -watch --only-published /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /tmp/templates:/etc/docker-gen/templates
  volumes_from:
    - nginx
```

@jwilder: Thanks for this great tool.

Greetings
Andy

**Comment by jwilder** [comment]
Thanks @andreaskoch!

**Comment by swapnil7434** [comment]
Hi,

I am getting following error.

[nginx-gen-1]2017-07-31T06:36:52.861965607Z 2017/07/31 06:36:52 Unable to parse template: open /etc/docker-gen/templates/nginx.tmpl: no such file or directory

can you please guide me what's wrong in that. Below is my configuration.

```
nginx:
  image: 'nginx:latest'
  labels:
    com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ''
  ports:
    - '80:80'
    - '443:443'
  tags:
    - app=cornerstone
    - env=dev
  volumes:
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - '/tmp/certs:/etc/nginx/certs:ro'
nginx-gen:
  command: '-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf'
  image: 'jwilder/docker-gen:latest'
  labels:
    com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: ''
  tags:
    - app=cornerstone
    - env=dev
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - '/tmp/templates:/etc/docker-gen/templates:ro'
  volumes_from:
    - nginx
nginx-letsencrypt:
  image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
  tags:
    - app=cornerstone
    - env=dev
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - '/tmp/certs:/etc/nginx/certs'
  volumes_from:
    - nginx
```
